{% set name = "airportsdata" %}
{% set version = "20241001" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/airportsdata-{{ version }}.tar.gz
  sha256: fa0bd143b4f4be3557cb892fa0612ef210fd91a92bd720b4d8221de576a4fa00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - airportsdata
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mborsetti/airportsdata
  summary: Extensive database of location and timezone data for nearly every airport and landing strip in the world.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
