{% set name = "airportsdata" %}
{% set version = "20260304" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/airportsdata-{{ version }}.tar.gz
  sha256: 7d8547182f33a555212705c0071cbbbf6b0c5b1f112c54c969b45797b66c1c4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - airportsdata
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mborsetti/airportsdata
  summary: Extensive database of location and timezone data for nearly every airport and landing strip in the world.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
